name: demo_video_series
description: Pipelines to load open meteo and NYC taxi data
version: 0.0.1
author: matthew+public_demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demovideoseries
  parentArtefactID: matthewpublicdemoprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-07-29 13:48:12'
pipelines:
  pipelines/Ingest_NYC_Taxi_Data:
    name: Ingest_NYC_Taxi_Data
    description: Ingest the NYC Taxi Data
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-29 13:48:12'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-29 13:48:12'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-07-29T13:48:12.021105Z'
  name: plibMaven
  version: 8.0.29
  id: '1437378150'
  createdAt: '2024-07-29T13:48:12.021105Z'
  type: plibMaven
- modifiedAt: '2024-07-29T13:48:12.021105Z'
  name: plibPypi
  version: 1.9.9
  id: '1708939715'
  createdAt: '2024-07-29T13:48:12.021105Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-29 13:03:23'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-29 13:03:23'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
